# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/Image/Image.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Image || ORIG_REF_NAME==Image} -quiet] -quiet

# XDC: ip/Image/Image_ooc.xdc
